[versions]
spring-boot-version = "2.7.18"
gson-version = "2.11.0"
kotlin-reflect-version = "2.0.0"

[plugins]

[libraries]
spring-boot-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot-version" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson-version" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin-reflect-version" }