[versions]
spring-boot-version = "2.7.18"
google-guava-version = "33.2.0-jre"

[plugins]

[libraries]
spring-boot-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot-version" }
guava = { module = "com.google.guava:guava", version.ref = "google-guava-version" }