[versions]
boot-plugin = "3.3.0"
google-guava = "33.2.0-jre"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "boot-plugin" }

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "google-guava" }